--- 
abstract: do horrible things to POD, producing better docs
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: Pod-Weaver
requires: 
  List::MoreUtils: 0
  Moose: 0
  Moose::Autobox: 0.08
  PPI: 0
  Pod::Elemental: 0
  Pod::Eventual::Simple: 0.004
  Software::License: 0
  String::Flogger: 1
  String::RewritePrefix: 0
  Test::Differences: 0
version: 2.001
