---
abstract: 'weave together a Pod document from an outline'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100651'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver
requires:
  Config::MVP: 0.093120
  Config::MVP::Assembler: 0
  Config::MVP::Assembler::WithBundles: 0
  Config::MVP::Reader: 0
  Config::MVP::Reader::Finder: 0
  Config::MVP::Reader::INI: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Autobox: 0.10
  Moose::Role: 0
  PPI: 0
  Pod::Elemental: 0.100220
  Pod::Elemental::Document: 0
  Pod::Elemental::Element::Nested: 0
  Pod::Elemental::Element::Pod5::Command: 0
  Pod::Elemental::Element::Pod5::Ordinary: 0
  Pod::Elemental::Element::Pod5::Region: 0
  Pod::Elemental::Element::Pod5::Verbatim: 0
  Pod::Elemental::Selectors: 0
  Pod::Elemental::Transformer::Gatherer: 0
  Pod::Elemental::Transformer::Nester: 0
  Pod::Elemental::Transformer::Pod5: 0
  Pod::Elemental::Types: 0
  Pod::Eventual::Simple: 0.004
  Software::License: 0
  Software::License::Artistic_1_0: 0
  String::Flogger: 1
  String::RewritePrefix: 0
  Test::Differences: 0
  Test::More: 0
  namespace::autoclean: 0
resources:
  repository: git://git.codesimply.com/Pod-Weaver.git
version: 3.100650
